# Form implementation generated from reading ui file 'AddPatient.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddPatient(object):
    def setupUi(self, AddPatient):
        AddPatient.setObjectName("AddPatient")
        AddPatient.resize(520, 379)
        AddPatient.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddPatient)
        self.buttonBox.setGeometry(QtCore.QRect(350, 340, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.name_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.name_LineEdit.setGeometry(QtCore.QRect(30, 20, 221, 31))
        self.name_LineEdit.setObjectName("name_LineEdit")
        self.name_LineEdit.setPlaceholderText("Имя")

        self.sername_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.sername_LineEdit.setGeometry(QtCore.QRect(30, 60, 221, 31))
        self.sername_LineEdit.setObjectName("sername_LineEdit")
        self.sername_LineEdit.setPlaceholderText("Фамилия")

        self.patronymic_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.patronymic_LineEdit.setGeometry(QtCore.QRect(30, 100, 221, 31))
        self.patronymic_LineEdit.setObjectName("patronymic_LineEdit")
        self.patronymic_LineEdit.setPlaceholderText("Отчество")

        self.birthda_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.birthda_LineEdit.setGeometry(QtCore.QRect(30, 140, 221, 31))
        self.birthda_LineEdit.setObjectName("birthda_LineEdit")
        self.birthda_LineEdit.setInputMask("00.00.0000")
        self.birthda_LineEdit.setToolTip("Дата рождения (в формате dd.mm.yyyy)")

        self.pasport_series_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.pasport_series_LineEdit.setGeometry(QtCore.QRect(30, 180, 221, 31))
        self.pasport_series_LineEdit.setObjectName("pasport_series_LineEdit")
        self.pasport_series_LineEdit.setInputMask("0000")
        self.pasport_series_LineEdit.setPlaceholderText("Серия паспорта (в формате 0000)")

        self.passport_num_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.passport_num_LineEdit.setGeometry(QtCore.QRect(30, 220, 221, 31))
        self.passport_num_LineEdit.setObjectName("passport_num_LineEdit")
        self.passport_num_LineEdit.setInputMask("000000")
        self.passport_num_LineEdit.setPlaceholderText("Номер паспорта (в формате 000000)")

        self.phone_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.phone_LineEdit.setGeometry(QtCore.QRect(30, 260, 221, 31))
        self.phone_LineEdit.setObjectName("phone_LineEdit")
        self.phone_LineEdit.setInputMask("0-000-000-00-00")
        self.phone_LineEdit.setToolTip("Номер телефона")

        self.email_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.email_LineEdit.setGeometry(QtCore.QRect(30, 300, 221, 31))
        self.email_LineEdit.setObjectName("email_LineEdit")
        self.email_LineEdit.setPlaceholderText("Почта")

        self.policy_LineEdit = QtWidgets.QLineEdit(parent=AddPatient)
        self.policy_LineEdit.setGeometry(QtCore.QRect(280, 120, 221, 31))
        self.policy_LineEdit.setObjectName("policy_LineEdit")
        self.policy_LineEdit.setPlaceholderText("Номер полиса")

        self.policy_type_ComboBox = QtWidgets.QComboBox(parent=AddPatient)
        self.policy_type_ComboBox.setGeometry(QtCore.QRect(280, 160, 221, 31))
        self.policy_type_ComboBox.setObjectName("policy_type_ComboBox")
        self.policy_type_ComboBox.setPlaceholderText("Тип полиса")

        self.insurance_company_ComboBox = QtWidgets.QComboBox(parent=AddPatient)
        self.insurance_company_ComboBox.setGeometry(QtCore.QRect(280, 200, 221, 31))
        self.insurance_company_ComboBox.setObjectName("insurance_company_ComboBox")
        self.insurance_company_ComboBox.setPlaceholderText("Страховая компания")

        self.retranslateUi(AddPatient)
        self.buttonBox.accepted.connect(AddPatient.accept) # type: ignore
        self.buttonBox.rejected.connect(AddPatient.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddPatient)

    def retranslateUi(self, AddPatient):
        _translate = QtCore.QCoreApplication.translate
        AddPatient.setWindowTitle(_translate("AddPatient", "Добавление пациента"))



